### ISSUE TITLE
interface leak on initial Request cancel

### ISSUE THREAD

**Issue by zolug** [networkservicemesh/cmd-forwarder-vpp#1133]
Interface can be leaked if the initial Request's context gets cancelled before the connection could be established.

The problem might occur in [kernelTap](https://github.com/networkservicemesh/sdk-vpp/tree/main/pkg/networkservice/mechanisms/kernel/kerneltap) if the context gets cancelled during the [vppConn tapCreate call](https://github.com/networkservicemesh/sdk-vpp/blob/main/pkg/networkservice/mechanisms/kernel/kerneltap/common.go#L80). In which case the call returns with an [error](https://github.com/networkservicemesh/sdk-vpp/blob/main/pkg/networkservice/mechanisms/kernel/kerneltap/common.go#L82), hence the interface won't get saved into the ifindex storage.

Therefore, even though the Request should initiate a Close due to the failed kernelTap create ([e.g. in kernelTapServer](https://github.com/networkservicemesh/sdk-vpp/blob/main/pkg/networkservice/mechanisms/kernel/kerneltap/server.go#L59)), [del](https://github.com/networkservicemesh/sdk-vpp/blob/main/pkg/networkservice/mechanisms/kernel/kerneltap/common.go#L145) won't be able to lookup the interface from the storage.

NSM version: v1.13.2-rc.1

**Logs:**

Follow the following request:
```
Jul  5 14:59:32.903 [TRAC] [id:9a29a6db-aed2-48d4-b5fa-c75f7337328e] [type:networkService] (1.1)   request={"connection":{"id":"9a29a6db-aed2-48d4-b5fa-c75f7337328e","network_service":"load-balancer-a1.trench-a.default","context":{"ip_context":{"src_ip_addrs":["172.16.0.31/24","fd00::1f/64"],"dst_ip_addrs":["172.16.0.30/24","fd00::1e/64"],"excluded_prefixes":["10.96.0.0/16","10.244.0.0/16"]},"MTU":1500},"labels":{"nodeName":"kind-worker3"},"path":{"index":1,"path_segments":[{"name":"proxy-load-balancer-a1-xvq6h","id":"f161b4b1-2ffa-4095-ace0-9d2027f4e356-proxy-load-balancer-a1-xvq6h-load-balancer-a1.trench-a.default-stateless-lb-frontend-attr-a1-f5864fc94-59nlh","token":"eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzcGlmZmU6Ly9leGFtcGxlLm9yZy9ucy9kZWZhdWx0L3NhL2RlZmF1bHQiLCJhdWQiOlsic3BpZmZlOi8vZXhhbXBsZS5vcmcvbnMvbnNtL3NhL25zbWdyLXNhIl0sImV4cCI6MTcyMDE5MjE3Mn0.Xz6pp29LEzAhDBFG4KBhQBMZ5BuL-GNQOP5e3l4NHPwEYRuLTg-FWlhAW2PO3SqQB67TLO6LRXzJ5rXlhV3dwA","expires":{"seconds":1720192172,"nanos":876126486},"metrics":{"client_interface":"KERNEL/unknown"}},{"name":"nsmgr-pbj2f","id":"9a29a6db-aed2-48d4-b5fa-c75f7337328e","token":"eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzcGlmZmU6Ly9leGFtcGxlLm9yZy9ucy9uc20vc2EvbnNtZ3Itc2EiLCJhdWQiOlsic3BpZmZlOi8vZXhhbXBsZS5vcmcvbnMvZGVmYXVsdC9zYS9kZWZhdWx0Il0sImV4cCI6MTcyMDE5MjE3Mn0.QamUnYKNhPziEGeN2hbFpNpKq2W8rtm0gZBiLaZ05lp0HSH9oVLsy54-vRblf5cUV5GK7gWlrbJdIc63sLDFaw","expires":{"seconds":1720192172,"nanos":877054244}}]},"network_service_endpoint_name":"stateless-lb-frontend-attr-a1-f5864fc94-59nlh","payload":"ETHERNET"},"mechanism_preferences":[{"cls":"LOCAL","type":"KERNEL","parameters":{"inodeURL":"inode://4/4026535834","name":"load-balan-2ezO"}}]}
```

Use filter string:
_load-balan-2ezO|9a29a6db-aed2-48d4-b5fa-c75f7337328e|95b833d9-10fc-43d4-9c30-54f2ad7f1c2b|load-balan-tZer_

NSC side _load-balan-2ezO_ interface will not be removed.
[nsm_forwarder-vpp-mwbc2_forwarder-vpp.log](https://github.com/user-attachments/files/16113635/nsm_forwarder-vpp-mwbc2_forwarder-vpp.log)

**Comment by zolug** [comment]
[nsm_forwarder-vpp-mwbc2_describe.log](https://github.com/user-attachments/files/16113660/nsm_forwarder-vpp-mwbc2_describe.log)

**Comment by zolug** [comment]
Another example where the NSE side interface _load-balan-t6nu_ got stuck.

```
Jul  5 14:59:33.372 [TRAC] [id:9a5ea784-40f2-4788-b286-c27f28eb9747] [type:networkService] (1.1)   request={"connection":{"id":"9a5ea784-40f2-4788-b286-c27f28eb9747","network_service":"load-balancer-a1.trench-a.default","context":{"ip_context":{"src_ip_addrs":["172.16.2.37/24","fd00:0:0:2::21/64"],"dst_ip_addrs":["172.16.2.36/24","fd00:0:0:2::20/64"],"excluded_prefixes":["10.96.0.0/16","10.244.0.0/16"]},"MTU":1500},"labels":{"nodeName":"kind-worker2"},"path":{"index":3,"path_segments":[{"name":"proxy-load-balancer-a1-77zlr","id":"991fe339-7d91-49d4-ba7f-2d4c1d7a01bd-proxy-load-balancer-a1-77zlr-load-balancer-a1.trench-a.default-stateless-lb-frontend-attr-a1-f5864fc94-59nlh","token":"eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzcGlmZmU6Ly9leGFtcGxlLm9yZy9ucy9kZWZhdWx0L3NhL2RlZmF1bHQiLCJhdWQiOlsic3BpZmZlOi8vZXhhbXBsZS5vcmcvbnMvbnNtL3NhL25zbWdyLXNhIl0sImV4cCI6MTcyMDE5MjE3Mn0.UUxJKoSOP-ee0Du3DstHxgecmKYzmpEnieVEBOdZiex8eUOpmA5P-KNr45hxsw-8PccGVUnNWcduISetmnQTNA","expires":{"seconds":1720192172,"nanos":880397227},"metrics":{"client_interface":"KERNEL/unknown"}},{"name":"nsmgr-pfss7","id":"a9211a4f-500d-4d7d-8a3b-ed44a173762e","token":"eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzcGlmZmU6Ly9leGFtcGxlLm9yZy9ucy9uc20vc2EvbnNtZ3Itc2EiLCJhdWQiOlsic3BpZmZlOi8vZXhhbXBsZS5vcmcvbnMvbnNtL3NhL2RlZmF1bHQiXSwiZXhwIjoxNzIwMTkyMTczfQ.9GqG4MtdzWz_F157_V0AF6CiCsl0rZxwNIEtattssADqMzl-An7EGGZV-WPqzZ5NqijLH0uq_-zmp1YZ9ii6nw","expires":{"seconds":1720192173,"nanos":76868291}},{"name":"forwarder-vpp-772b9","id":"789260f9-be2e-401a-b601-40b3a913c067","token":"eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzcGlmZmU6Ly9leGFtcGxlLm9yZy9ucy9uc20vc2EvZGVmYXVsdCIsImF1ZCI6WyJzcGlmZmU6Ly9leGFtcGxlLm9yZy9ucy9uc20vc2EvbnNtZ3Itc2EiXSwiZXhwIjoxNzIwMTkyMTczfQ.KA1890RkZBfrFcYBiytD6HLZp-DctqnJ27yJY-eOVqVE4bjsX-VPQ44Vn5mRnbos85sXxngjec2sxFtoUwbStQ","expires":{"seconds":1720192173,"nanos":183239052}},{"name":"nsmgr-pbj2f","id":"9a5ea784-40f2-4788-b286-c27f28eb9747","token":"eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzcGlmZmU6Ly9leGFtcGxlLm9yZy9ucy9uc20vc2EvbnNtZ3Itc2EiLCJhdWQiOlsic3BpZmZlOi8vZXhhbXBsZS5vcmcvbnMvbnNtL3NhL2RlZmF1bHQiXSwiZXhwIjoxNzIwMTkyMTczfQ.cqMK_9_P-J9tkEkCATe0-lZgej5FO7OJg-918c_MRaj70aB1SFK86sWvb1VQW_5fbbpFxfl9jjUA-rkrF2svOQ","expires":{"seconds":1720192173,"nanos":184038754}}]},"network_service_endpoint_name":"stateless-lb-frontend-attr-a1-f5864fc94-59nlh","payload":"ETHERNET"},"mechanism_preferences":[{"cls":"REMOTE","type":"VXLAN","parameters":{"MTU":"1446","src_ip":"172.18.0.6","src_port":"4789"}},{"cls":"REMOTE","type":"VLAN"}]}
```

filter string:
load-balan-t6nu|667aa022-1a1a-49ec-a938-37b9dddb2da6|9a5ea784-40f2-4788-b286-c27f28eb9747

(same forwarder logs)

**Comment by zolug** [comment]
I was able to reproduce it on a 4 node KIND cluster relying on basic deployment with kernel-nse and kernel-nsc by tweaking NSM_REQUEST_TIMEOUT parameter.

Double checked that in nsc the requests kept failing due to context timeout, and left the system running for a couple minutes and was monitoring forwarder logs for "vppapi TapCreateV3 returned error" printouts.

```
cat <<EOF | kubectl apply -f -
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsc-kernel
  labels:
    app: nsc-kernel
spec:
  selector:
    matchLabels:
      app: nsc-kernel
  template:
    metadata:
      labels:
        app: nsc-kernel
        "spiffe.io/spiffe-id": "true"
    spec:
      initContainers:
        - name: sysctl-init
          image: registry.nordix.org/cloud-native/meridio/busybox:1.29
          securityContext:
            privileged: true
          command: ["/bin/sh"]
          args:
            - -c
            - sysctl -w net.ipv4.ping_group_range='0 1' ;
      containers:
        - name: nsc
          image: ghcr.io/networkservicemesh/cmd-nsc:v1.13.2-rc.1
          imagePullPolicy: Always
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSM_LOG_LEVEL
              value: TRACE
            - name: NSM_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NSM_NETWORK_SERVICES
              value: kernel://icmp-responder
            - name: NSM_LIVENESSCHECKENABLED
              value: "false"
            - name: NSM_REQUEST_TIMEOUT
              value: "180ms"
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 40Mi
            limits:
              memory: 80Mi
              cpu: 200m
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: nsm-socket
          hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
EOF



cat <<EOF | kubectl apply -f -
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nse-kernel
  labels:
    app: nse-kernel
spec:
  selector:
    matchLabels:
      app: nse-kernel
  template:
    metadata:
      labels:
        app: nse-kernel
        "spiffe.io/spiffe-id": "true"
    spec:
      containers:
        - name: nse
          image: ghcr.io/networkservicemesh/cmd-nse-icmp-responder:v1.13.2-rc.1
          imagePullPolicy: IfNotPresent
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NSM_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NSM_LOG_LEVEL
              value: TRACE
            - name: NSM_CONNECT_TO
              value: unix:///var/lib/networkservicemesh/nsm.io.sock
            - name: NSM_CIDR_PREFIX
              value: 172.16.0.0/16
            - name: NSM_SERVICE_NAMES
              value: "icmp-responder"
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 40Mi
            limits:
              memory: 80Mi
              cpu: 200m
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: nsm-socket
          hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
EOF
```

```
NAME                          READY   STATUS    RESTARTS   AGE   IP            NODE           NOMINATED NODE   READINESS GATES
nsc-kernel-7cc77f58c8-ftl7f   1/1     Running   0          30m   10.244.1.12   kind-worker2   <none>           <none>
nse-kernel-85fbcffb44-ghz5s   1/1     Running   0          30m   10.244.2.9    kind-worker    <none>           <none>


kubectl get pods -l app=nsc-kernel -o=jsonpath='{.items[*].metadata.name}'| tr ' ' '\n' | xargs -I{} sh -c 'echo === {} === && kubectl exec -t {}  -- ip a';kubectl get pods -l app=nse-kernel -o=jsonpath='{.items[*].metadata.name}'| tr ' ' '\n' | xargs -I{} sh -c 'echo === {} === && kubectl exec -t {}  -- ip a'
=== nsc-kernel-7cc77f58c8-ftl7f ===
Defaulted container "nsc" out of: nsc, sysctl-init (init)
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0@if15: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP 
    link/ether 1e:5f:01:00:e9:70 brd ff:ff:ff:ff:ff:ff
    inet 10.244.1.12/24 brd 10.244.1.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::1c5f:1ff:fe00:e970/64 scope link 
       valid_lft forever preferred_lft forever
=== nse-kernel-85fbcffb44-ghz5s ===
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0@icmp-respo-Rw5D: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP 
    link/ether 9a:ea:0c:ea:b3:2e brd ff:ff:ff:ff:ff:ff
    inet 10.244.2.9/24 brd 10.244.2.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::98ea:cff:feea:b32e/64 scope link 
       valid_lft forever preferred_lft forever
3: icmp-respo-CTW4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:03:96:b0:a1 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:3ff:fe96:b0a1/64 scope link 
       valid_lft forever preferred_lft forever
4: icmp-respo-SSwm: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:5b:6a:f2:04 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:5bff:fe6a:f204/64 scope link 
       valid_lft forever preferred_lft forever
5: icmp-respo-ePzm: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:11:74:cb:fa brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:11ff:fe74:cbfa/64 scope link 
       valid_lft forever preferred_lft forever
6: icmp-respo-yJZR: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:6b:54:49:71 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:6bff:fe54:4971/64 scope link 
       valid_lft forever preferred_lft forever
7: icmp-respo-QShs: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:57:ae:f2:13 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:57ff:feae:f213/64 scope link 
       valid_lft forever preferred_lft forever
8: icmp-respo-rFaQ: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:19:d3:7a:09 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:19ff:fed3:7a09/64 scope link 
       valid_lft forever preferred_lft forever
9: icmp-respo-rg7S: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:f3:44:29:86 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:f3ff:fe44:2986/64 scope link 
       valid_lft forever preferred_lft forever
10: icmp-respo-A6cp: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:fb:2f:3e:1a brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:fbff:fe2f:3e1a/64 scope link 
       valid_lft forever preferred_lft forever
11: icmp-respo-Rw5D: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:01:11:de:76 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:1ff:fe11:de76/64 scope link 
       valid_lft forever preferred_lft forever
12: icmp-respo-r4Db: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:97:4a:57:2f brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:97ff:fe4a:572f/64 scope link 
       valid_lft forever preferred_lft forever
13: icmp-respo-KvCJ: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:29:d6:43:50 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:29ff:fed6:4350/64 scope link 
       valid_lft forever preferred_lft forever
14: icmp-respo-z0kO: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:3d:95:f7:58 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:3dff:fe95:f758/64 scope link 
       valid_lft forever preferred_lft forever
15: icmp-respo-V3EG: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:bd:60:0b:8e brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:bdff:fe60:b8e/64 scope link 
       valid_lft forever preferred_lft forever
16: icmp-respo-CRvI: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:21:ad:cc:f0 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:21ff:fead:ccf0/64 scope link 
       valid_lft forever preferred_lft forever
17: icmp-respo-ipuI: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:f9:e7:d9:db brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:f9ff:fee7:d9db/64 scope link 
       valid_lft forever preferred_lft forever
18: icmp-respo-3zFH: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:b9:f8:db:d7 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:b9ff:fef8:dbd7/64 scope link 
       valid_lft forever preferred_lft forever
19: icmp-respo-sDW0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:e7:d7:c3:17 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:e7ff:fed7:c317/64 scope link 
       valid_lft forever preferred_lft forever
20: icmp-respo-GLAw: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:49:d9:c5:99 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:49ff:fed9:c599/64 scope link 
       valid_lft forever preferred_lft forever
21: icmp-respo-shCm: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:2f:2f:e2:d3 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:2fff:fe2f:e2d3/64 scope link 
       valid_lft forever preferred_lft forever
22: icmp-respo-erCg: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:d1:20:9a:a2 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:d1ff:fe20:9aa2/64 scope link 
       valid_lft forever preferred_lft forever
23: icmp-respo-AztN: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:e7:69:12:57 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:e7ff:fe69:1257/64 scope link 
       valid_lft forever preferred_lft forever
24: icmp-respo-u8VJ: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:f1:49:85:66 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:f1ff:fe49:8566/64 scope link 
       valid_lft forever preferred_lft forever
25: icmp-respo-xviy: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:b1:fa:1b:ca brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:b1ff:fefa:1bca/64 scope link 
       valid_lft forever preferred_lft forever
26: icmp-respo-MCO7: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:19:b2:6d:09 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:19ff:feb2:6d09/64 scope link 
       valid_lft forever preferred_lft forever
27: icmp-respo-wqOy: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:9f:8f:eb:19 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:9fff:fe8f:eb19/64 scope link 
       valid_lft forever preferred_lft forever
28: icmp-respo-DalE: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:3f:d4:d8:b1 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:3fff:fed4:d8b1/64 scope link 
       valid_lft forever preferred_lft forever
29: icmp-respo-iryd: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:73:72:8d:3b brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:73ff:fe72:8d3b/64 scope link 
       valid_lft forever preferred_lft forever
30: icmp-respo-GNxN: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:b7:97:05:0d brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:b7ff:fe97:50d/64 scope link 
       valid_lft forever preferred_lft forever
31: icmp-respo-c957: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:6b:05:d8:ad brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:6bff:fe05:d8ad/64 scope link 
       valid_lft forever preferred_lft forever
32: icmp-respo-uxJE: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:7f:55:07:47 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:7fff:fe55:747/64 scope link 
       valid_lft forever preferred_lft forever
33: icmp-respo-jXu5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:3f:85:51:95 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:3fff:fe85:5195/64 scope link 
       valid_lft forever preferred_lft forever
34: icmp-respo-uX9z: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:ed:17:52:30 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:edff:fe17:5230/64 scope link 
       valid_lft forever preferred_lft forever
35: icmp-respo-ctZo: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:79:82:1b:3f brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:79ff:fe82:1b3f/64 scope link 
       valid_lft forever preferred_lft forever
36: icmp-respo-x7yM: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:47:c8:fe:7b brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:47ff:fec8:fe7b/64 scope link 
       valid_lft forever preferred_lft forever
37: icmp-respo-bW5f: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:1b:99:19:32 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:1bff:fe99:1932/64 scope link 
       valid_lft forever preferred_lft forever
38: icmp-respo-oO3g: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:f7:81:66:7a brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:f7ff:fe81:667a/64 scope link 
       valid_lft forever preferred_lft forever
39: icmp-respo-NPQR: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:01:07:78:69 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:1ff:fe07:7869/64 scope link 
       valid_lft forever preferred_lft forever
40: icmp-respo-qrmC: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:17:89:31:f0 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:17ff:fe89:31f0/64 scope link 
       valid_lft forever preferred_lft forever
41: icmp-respo-CRCU: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:4b:51:7a:13 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:4bff:fe51:7a13/64 scope link 
       valid_lft forever preferred_lft forever
42: icmp-respo-GdjO: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:43:56:de:1a brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:43ff:fe56:de1a/64 scope link 
       valid_lft forever preferred_lft forever
43: icmp-respo-uNRG: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:bf:22:a5:e5 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:bfff:fe22:a5e5/64 scope link 
       valid_lft forever preferred_lft forever
44: icmp-respo-U7wo: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:c3:80:c3:b1 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:c3ff:fe80:c3b1/64 scope link 
       valid_lft forever preferred_lft forever
45: icmp-respo-k3p8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN qlen 1000
    link/ether 02:fe:ad:ee:8c:db brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fe:adff:feee:8cdb/64 scope link tentative 
       valid_lft forever preferred_lft forever


```
