### ISSUE TITLE
NSE has not interface in kernel local use-case

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/cmd-forwarder-vpp#34]
## Forwarder vpp deployment

```
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: forwarder-vpp
  labels:
    app: forwarder-vpp
spec:
  selector:
    matchLabels:
      app: forwarder-vpp
  template:
    metadata:
      labels:
        app: forwarder-vpp
    spec:
      containers:
        - image: networkservicemeshci/cmd-forwarder-vpp:latest
          imagePullPolicy: IfNotPresent
          name: forwarder-vpp
          securityContext:
            privileged: true
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSM_TUNNEL_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NSM_CONNECT_TO
              value: unix:///var/lib/networkservicemesh/nsm.io.sock
            - name: NSM_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: nsm-socket
          hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate

```

## Steps to reproduce:

1. Use deployment that described above 
2. Follow steps: https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/memory (for local usecase)
3. Run `ifconfig` in nse

Actual:
```
eth0      Link encap:Ethernet  HWaddr BA:22:C2:E9:DA:8F  
          inet addr:10.244.2.10  Bcast:10.244.2.255  Mask:255.255.255.0
          inet6 addr: fe80::b822:c2ff:fee9:da8f/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:10 errors:0 dropped:0 overruns:0 frame:0
          TX packets:22 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:1374 (1.3 KiB)  TX bytes:1662 (1.6 KiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:6 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
```
Expected: nsm interface is created

## Logs
[nse.txt](https://github.com/networkservicemesh/cmd-forwarder-vpp/files/5862214/nse.txt)
[forwarder-vpp.txt](https://github.com/networkservicemesh/cmd-forwarder-vpp/files/5862215/forwarder-vpp.txt)
[nsc.txt](https://github.com/networkservicemesh/cmd-forwarder-vpp/files/5862216/nsc.txt)
