### ISSUE TITLE
vpp bridge created with serious delay for vlan connection

### ISSUE THREAD

**Issue by zolug** [networkservicemesh/cmd-forwarder-vpp#781]
This issue is related to the following PR:  https://github.com/networkservicemesh/sdk-vpp/pull/634

When an NSM connection is set up to a service provided by Remote VLAN NSE, the interface injected into the NSC POD is not usable for minutes. According to vppcli the bridge wasn't available (present) and showed up with the same delay.

What seemingly fixes the "connection"/bridge is the first refresh of the NSM connection.
Also, I rebuilt forwarder-vpp on the version where above changed got included, and run that forwarder on NSM v1.6 with the same results.

Note: When testing preliminary drop of the feature such delay was not visible, unfortunately I have no information of its code base (image = registry.nordix.org/cloud-native/nsm/cmd-forwarder-vpp:with-bd-wout-mac).

Reproduction (on Kind):
- Install NSM basic  (v1.7-rc1). Or rebuild forwarder-vpp on commit 5ed4cbb45dd25ee using it with NSM v1.6 components.
- Deploy a Remote VLAN NSE and NSC.
```

cat <<EOF | kubectl apply -f -
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nse-vlan
  labels:
    app: nse-vlan
spec:
  selector:
    matchLabels:
      app: nse-vlan
  template:
    metadata:
      labels:
        app: nse-vlan
        "spiffe.io/spiffe-id": "true"
    spec:
      containers:
        - name: nse
          image: registry.nordix.org/cloud-native/nsm/cmd-nse-remote-vlan:v1.6.0
          imagePullPolicy: Always
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSM_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NSM_LOG_LEVEL
              value: TRACE
            - name: NSM_CONNECT_TO
              value: "nsm-registry-svc.nsm:5002"
            - name: NSM_CIDR_PREFIX
              value: "169.254.100.0/24,100:100::/64"
            - name: NSM_SERVICES
              value: "vlan-svc { vlan: 100; via: eth0 }"
            - name: NSM_LISTEN_ON
              value: "tcp://:5003"
            - name: NSM_POINT2POINT
              value: "False"
            - name: NSM_REGISTER_SERVICE
              value: "True"
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 40Mi
            limits:
              memory: 80Mi
              cpu: 200m
      nodeSelector:
        kubernetes.io/hostname: kind-worker2
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
EOF

cat <<EOF | kubectl apply -f -
---
apiVersion: v1
kind: Pod
metadata:
  name: nsc
  labels:
    app: nsc  
    "spiffe.io/spiffe-id": "true"
spec:
  containers:
  - name: nsc
    image: registry.nordix.org/cloud-native/nsm/cmd-nsc:v1.6.0
    imagePullPolicy: Always
    env:
      - name: NSM_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: SPIFFE_ENDPOINT_SOCKET
        value: unix:///run/spire/sockets/agent.sock
      - name: NSM_LOG_LEVEL
        value: TRACE
      - name: NSM_NETWORK_SERVICES
        value: kernel://vlan-svc/ext-1
      - name: NSM_LIVENESSCHECKENABLED
        value: "false"
      - name: NSM_LOCALDNSSERVERENABLED
        value: "false"
      - name: NSM_DIAL_TIMEOUT
        value: "30s"
      - name: NSM_REQUEST_TIMEOUT
        value: "300s"
    volumeMounts:
      - name: spire-agent-socket
        mountPath: /run/spire/sockets
        readOnly: true
      - name: nsm-socket
        mountPath: /var/lib/networkservicemesh
        readOnly: true
    resources:
      requests:
        cpu: 100m
        memory: 40Mi
      limits:
        memory: 80Mi
        cpu: 200m
  volumes:
    - name: spire-agent-socket
      hostPath:
        path: /run/spire/sockets
        type: Directory
    - name: nsm-socket
      hostPath:
        path: /var/lib/networkservicemesh
        type: DirectoryOrCreate
  nodeSelector:
    kubernetes.io/hostname: kind-worker
EOF
  

```
- Check vppcli on the forwarder hosting the NSC to see the delayed appearance of the bridge (while the NSC connection is already established): 
```
root@kind-worker:/# vppctl show bridge-domain
no bridge-domains in use
```

Logs:
forwarder-vpp-ddqqp.5ed4cbb45dd25ee.log collocated with the NSC
First Request for service vlan-svc at Dec 15 14:51:22.210.
Refreshed at Dec 15 14:53:22.291 after which the bridge appeared in vpp.
```
root@kind-worker:/# date; vppctl show bridge-domain
Thu Dec 15 14:53:28 UTC 2022
  BD-ID   Index   BSN  Age(min)  Learning  U-Forwrd   UU-Flood   Flooding  ARP-Term  arp-ufwd Learn-co Learn-li   BVI-Intf 
 7271263    1      0     off        on        on       flood        on       off       off        0    16777216     N/A    
root@kind-worker:/# date; vppctl show bridge-domain 7271263 details
Thu Dec 15 14:53:37 UTC 2022
  BD-ID   Index   BSN  Age(min)  Learning  U-Forwrd   UU-Flood   Flooding  ARP-Term  arp-ufwd Learn-co Learn-li   BVI-Intf 
 7271263    1      0     off        on        on       flood        on       off       off        0    16777216     N/A    
             SPAN (span-l2-input)
   INPUT_CLASSIFY (l2-input-classify)
   INPUT_FEAT_ARC (l2-input-feat-arc)
     POLICER_CLAS (l2-policer-classify)
              ACL (l2-input-acl)
            VPATH (vpath-input-l2)
 L2_IP_QOS_RECORD (l2-ip-qos-record)
              VTR (l2-input-vtr)
            LEARN (l2-learn)
               RW (l2-rw)
              FWD (l2-fwd)
         UU_FLOOD (l2-flood)
            FLOOD (l2-flood)
         XCONNECT (l2-output)

           Interface           If-idx ISN  SHG  BVI  TxFlood        VLAN-Tag-Rewrite       
             tap0                3     1    1    -      *                 none             
         host-eth0.100           2     1    0    -      *                 pop-1   
```
